name: Build and Publish docker image

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
  release:
    types: [published, edited]

jobs:
  publish-docker-release:
    name: Publish Docker Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: dairlair/mediagrabber-base
          tag_with_ref: true

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: dairlair/mediagrabber/mediagrabber
          tag_with_ref: true
